version: '3.9'

services:
  api-cover:
    container_name: api-cover
    build:
      context: .
      dockerfile: Dockerfile.cover
    depends_on:
      - 'db'
    ports:
      - '8080:80'
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      DataAccess__ConnectionString: "Server=db;Database=money-help;User Id=SA;Password=Password123;TrustServerCertificate=True;"

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password123'
